### ISSUE TITLE
V2 - Method does not implement baseUriParameters()

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#107]
This exception is thrown:

    java.lang.RuntimeException: Method not found:   org.raml.v2.internal.impl.commons.model.Method.baseUriParameters
      at org.raml.v2.internal.impl.commons.model.builder.ModelProxyBuilder$SimpleProxy.findMatchingMethod(ModelProxyBuilder.java:124)
      at org.raml.v2.internal.impl.commons.model.builder.ModelProxyBuilder$SimpleProxy.invoke(ModelProxyBuilder.java:61)
      at com.sun.proxy.$Proxy11.baseUriParameters(Unknown Source)

**Comment by sichvoge** [comment]
That surely should be implemented since `baseUriParameters` is only supported at the root-level.

**Comment by nidi3** [comment]
I meant in the **v0.8** parser of v2, where baseUriParameters on methods are allowed.

**Comment by sichvoge** [comment]
Ah ok! Missed that.

**Comment by svacas** [comment]
fixed in c43d5b788e22932d12a21e055ac2d52fa8843ece
