### ISSUE TITLE
[TCK] TC012 API - Title must accept numbers

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-java-parser#123]
Parsing the following RAML

```yaml
#%RAML 1.0
title: 54
baseUri: http://myapi.com
```
Actual result:
Exception in thread "main" java.lang.ClassCastException: org.raml.yagi.framework.nodes.snakeyaml.SYIntegerNode cannot be cast to org.raml.yagi.framework.nodes.StringNode
	at org.raml.yagi.framework.grammar.rule.MinLengthRule.apply(MinLengthRule.java:62)
	at org.raml.yagi.framework.grammar.rule.AllOfRule.apply(AllOfRule.java:98)
	at org.raml.yagi.framework.grammar.rule.AnyOfRule.apply(AnyOfRule.java:102)
	at org.raml.yagi.framework.grammar.rule.FirstOfRule.apply(FirstOfRule.java:55)
	at org.raml.yagi.framework.grammar.rule.KeyValueRule.apply(KeyValueRule.java:136)
	at org.raml.yagi.framework.grammar.rule.ObjectRule.apply(ObjectRule.java:153)
	at org.raml.yagi.framework.phase.GrammarPhase.apply(GrammarPhase.java:38)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:88)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:73)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:110)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:78)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:69)
	at org.raml.v2.internal.impl.RamlValidator.validateRaml(RamlValidator.java:87)
	at org.raml.v2.internal.impl.RamlValidator.validate(RamlValidator.java:59)
	at org.raml.v2.internal.impl.RamlValidator.validate(RamlValidator.java:46)
	at org.raml.v2.internal.impl.RamlValidator.main(RamlValidator.java:117)

Expected result:
The RAML file must be parsed successfully

**Comment by svacas** [comment]
fixed by 66d516ee3cbfa02cbfb77613f0d4bd075fe7fee8
