### ISSUE TITLE
Exception on trait-defined query parameter when facet value is parameterized

### ISSUE THREAD

**Issue by quilicicf** [raml-org/raml-java-parser#190]
#### Code executed

```java

package com.restlet.definitions.raml10.reader;

import org.raml.v2.api.RamlModelBuilder;
import org.raml.v2.api.RamlModelResult;
import org.raml.v2.api.model.v10.api.Api;
import org.raml.v2.api.model.v10.datamodel.TypeDeclaration;
import org.raml.v2.api.model.v10.methods.Method;
import org.raml.v2.api.model.v10.resources.Resource;

import java.nio.file.Paths;

public class Test {

    // TODO: update the path to match your system's installation
    private static final String FOLDER = "/local/path/to/raml-java-parser/raml-parser-2/src/test/resources/org/raml/v2/parser/examples/";
    public static void main(String[] args) throws Exception {
        String savedRamlLocation = Paths.get(FOLDER + "slideshare/input.raml").toUri().toURL().toString();
        RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(savedRamlLocation);

        Api savedRaml = ramlModelResult.getApiV10();
        Resource firstResource = savedRaml.resources().get(0); // /get_slideshow
        Method method = firstResource.methods().get(0); // GET method
        TypeDeclaration parameter = method.queryParameters().get(4); // Paremeter username, from trait canFetchPersonalData
        parameter.required(); // => fails
    }
}
```

#### Example used

https://github.com/raml-org/raml-java-parser/blob/035522b2ecad11b8cc93da562e3c4bcf72a5eb5b/raml-parser-2/src/test/resources/org/raml/v2/parser/examples/slideshare/input.raml

#### Stack trace

```
Exception in thread "main" java.lang.RuntimeException: Internal error while trying to call public abstract java.lang.Boolean org.raml.v2.api.model.v10.datamodel.TypeDeclaration.required()
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.invoke(ModelProxyBuilder.java:79)
	at com.sun.proxy.$Proxy3.required(Unknown Source)
	at com.restlet.definitions.raml10.reader.Test.main(Test.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.fromMethod(ModelProxyBuilder.java:98)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.invoke(ModelProxyBuilder.java:74)
	... 7 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at org.raml.v2.internal.impl.commons.model.type.TypeDeclaration.required(TypeDeclaration.java:146)
	... 13 more
```

**Comment by svacas** [comment]
Can you check if this is still failing?
I cannot reproduce it with the latest changes

**Comment by quilicicf** [comment]
Sorry for the delay, I was on vacation it works on my side yes thanks ! :+
