### ISSUE TITLE
v08 type "date" causes NPE

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#290]
```
#%RAML 0.8
title: type
baseUri: http://nidi.guru/raml/v1

/type:
  get:
    queryParameters:
      date:
        type: date
```

gives

```

java.lang.RuntimeException: Internal error while trying to call public abstract java.util.List<org.raml.v2.api.model.v08.parameters.Parameter> org.raml.v2.api.model.v08.methods.MethodBase.queryParameters()

	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.invoke(ModelProxyBuilder.java:79)
	at com.sun.proxy.$Proxy11.queryParameters(Unknown Source)
	at guru.nidi.ramltester.model.Method08.queryParameters(Method08.java:58)
Caused by: java.lang.NullPointerException
	at org.raml.v2.internal.impl.commons.model.factory.TypeDeclarationModelFactory$NodeModelTypeFactory.create(TypeDeclarationModelFactory.java:213)
	at org.raml.v2.internal.impl.commons.model.factory.TypeDeclarationModelFactory.create(TypeDeclarationModelFactory.java:71)
	at org.raml.v2.internal.impl.commons.model.factory.TypeDeclarationModelFactory.create(TypeDeclarationModelFactory.java:60)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.resolveValue(ModelProxyBuilder.java:192)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.resolveValue(ModelProxyBuilder.java:164)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.fromNodeKey(ModelProxyBuilder.java:88)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.invoke(ModelProxyBuilder.java:70)
	... 38 more
```

**Comment by mpviau** [comment]
Same issue here

**Comment by rscadrde** [comment]
With raml 1.0 it is
`type: date-only`
instead of
`type: date`
