### ISSUE TITLE
Parsing fails when an example references an array property and the items attribute is missing

### ISSUE THREAD

**Issue by boillodmanuel** [raml-org/raml-java-parser#300]
Version: 1.0.2

For example, this RAML

``` yaml
#%RAML 1.0
title: array error
version: v1
types:
    DummyObject:
      type: object
      properties:
        id: integer
        dummyList:
          type: array

/send:
  post:
    body:
      application/json:
        type: DummyObject
        example: {"id":2, "dummyList":["27824133473"]}
```

generates:

```
Caused by: java.lang.NullPointerException
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.generateRule(TypeToRuleVisitor.java:89)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitArray(TypeToRuleVisitor.java:323)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitArray(TypeToRuleVisitor.java:66)
    at org.raml.v2.internal.impl.v10.type.ArrayResolvedType.visit(ArrayResolvedType.java:149)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.generateRule(TypeToRuleVisitor.java:89)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitObject(TypeToRuleVisitor.java:158)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitObject(TypeToRuleVisitor.java:66)
    at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.visit(ObjectResolvedType.java:275)
    at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.validate(ExampleValidationPhase.java:126)
    at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.apply(ExampleValidationPhase.java:81)
    at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
    at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:110)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:98)
    at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:124)
    at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:114)
```

**Comment by LorenaSoledad** [comment]
Hi @boillodmanuel, we are currently working on a solution to solve this issue

**Comment by boillodmanuel** [comment]
Great!
Thanks for the follow up.
