### ISSUE TITLE
A sexagesimal number as invalid date causes exception

### ISSUE THREAD

**Issue by nidi3** [raml-org/raml-java-parser#324]
```
when:
    type: datetime
    example: 12:34.5
      
```
causes
```
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:470)
	at java.math.BigDecimal.<init>(BigDecimal.java:739)
	at org.raml.yagi.framework.nodes.snakeyaml.SYFloatingNode.getValue(SYFloatingNode.java:44)
	at org.raml.yagi.framework.nodes.snakeyaml.SYFloatingNode.toString(SYFloatingNode.java:50)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.raml.yagi.framework.grammar.rule.ErrorNodeFactory.createInvalidNode(ErrorNodeFactory.java:45)
	at org.raml.yagi.framework.grammar.rule.DateValueRule.apply(DateValueRule.java:75)
	at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.validate(ExampleValidationPhase.java:127)
	at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.apply(ExampleValidationPhase.java:81)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:116)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:100)
	at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:125)
	at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:93)
```

**Comment by nidi3** [comment]
This kind of exception could occur everwhere a `SYFloatingNode` is tried to convert into a `BigDecimal`.

**Comment by machaval** [comment]
Fixed
