### ISSUE TITLE
cannot  get headers of trait

### ISSUE THREAD

**Issue by diablonhn** [raml-org/raml-java-parser#368]
```
#%RAML 0.8
---
title: title0

traits:
    - vehicle: !include traits/vehicleHeader.yml
/path0:
    get:
        is: [vehicle]
```

**traits/vehicleHeader.yml**:
```
headers:
    traitHeader0:
    traitHeader1:
```

In raml-java-parser-1.0.8, calling:
```
    Trait trait = traitRef.trait();
    trait.getHeaders();
```

throws the following exception:

```
java.lang.RuntimeException: Internal error while trying to call public abstract java.util.List<org.raml.v2.api.model.v08.parameters.Parameter> org.raml.v2.api.model.v08.methods.MethodBase.headers()

	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.invoke(ModelProxyBuilder.java:79)
	at com.sun.proxy.$Proxy9.headers(Unknown Source)
Caused by: java.lang.RuntimeException: Invalid node for type creation class org.raml.yagi.framework.nodes.KeyValueNodeImpl
	at org.raml.v2.internal.impl.commons.model.factory.TypeDeclarationModelFactory.create(TypeDeclarationModelFactory.java:82)
	at org.raml.v2.internal.impl.commons.model.factory.TypeDeclarationModelFactory.create(TypeDeclarationModelFactory.java:61)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.resolveValue(ModelProxyBuilder.java:192)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.resolveValue(ModelProxyBuilder.java:164)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.fromNodeKey(ModelProxyBuilder.java:88)
	at org.raml.yagi.framework.model.ModelProxyBuilder$SimpleProxy.invoke(ModelProxyBuilder.java:70)
```

**Comment by leoeros** [comment]
there is a same exception occupied when call trait.queryParameters() method.

**Comment by zoldik1** [comment]
dia all on west, charles, zoldik, agri etc go there

**Comment by diablonhn** [comment]
But where manmen?  No fun.
________________________________
