### ISSUE TITLE
Null pointer exception in DiscriminatorBasedRule

### ISSUE THREAD

**Issue by KevinMitchell** [raml-org/raml-java-parser#511]
Hi,

Using the latest version of the parser, 1.0.23-SNAPSHOT, I'm getting a NPE with this example:

```
#%RAML 1.0
title: Title
uses:
  test: lib.raml
```
```
#%RAML 1.0 Library
types:
  Foo:
    discriminator: type
    properties:
      type:

  Bar:
    type: Foo
    discriminatorValue: v
    example:
      type: v
```
I've tried to prune the example down to the bare minimum that produces the failure.  It seemed to require the auxiliary library to fail.

Here's the stack trace in case it's useful:
```
Exception in thread "main" java.lang.NullPointerException
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.findTypeDeclarationField(DiscriminatorBasedRule.java:140)
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.findTypeDeclarationField(DiscriminatorBasedRule.java:150)
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.findTypeDeclarationField(DiscriminatorBasedRule.java:152)
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.findTypeDeclarationField(DiscriminatorBasedRule.java:152)
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.findTypeDeclarationField(DiscriminatorBasedRule.java:152)
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.findTypeDeclaration(DiscriminatorBasedRule.java:113)
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.findType(DiscriminatorBasedRule.java:95)
	at org.raml.v2.internal.impl.v10.rules.DiscriminatorBasedRule.apply(DiscriminatorBasedRule.java:76)
	at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.validate(ExampleValidationPhase.java:139)
	at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.apply(ExampleValidationPhase.java:88)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:123)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:102)
	at org.raml.v2.internal.impl.v10.phase.LibraryLinkingTransformation.transform(LibraryLinkingTransformation.java:70)
	at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:45)
	at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:123)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:102)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:74)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:123)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:105)
	at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:125)
	at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:93)
	at com.avaloq.api.test.App.main(App.java:55)
```

**Comment by torpex77** [comment]
FWIW, I have bumped into the same issue under the same scenario - discriminators in an included library.
