### ISSUE TITLE
mvn clean package -P jar-with-dependencies is failing with Errors.

### ISSUE THREAD

**Issue by rpatani** [raml-org/raml-java-parser#598]
========================================================================================================================
Tests run: 345, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.196 sec <<< FAILURE!
runTest[xml-to-raml-type-validations.array-error](org.raml.v2.parser.RamlBuilderTestCase)  Time elapsed: 0.072 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: equalToIgnoringWhiteSpace("RamlDocumentNode (Start: 11 , End: 423, On: input.raml, Source: SYObjectNode)\n    KeyValueNodeImpl (Start: 11 , End: 31, On: input.raml)\n        SYStringNode: \"title\" (Start: 11 , End: 16, On: input.raml)\n        OverlayableObjectNodeImpl (Start: 18 , End: 31, On: input.raml, Source: SYStringNode)\n            KeyValueNodeImpl (Start: 11 , End: 31, On: input.raml)\n                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                OverlayableStringNode: \"simple object\" (Start: 18 , End: 31, On: input.raml)\n    TypesNode (Start: 32 , End: 200, On: input.raml, Source: KeyValueNodeImpl)\n        SYStringNode: \"types\" (Start: 32 , End: 37, On: input.raml)\n        SYObjectNode (Start: 41 , End: 200, On: input.raml)\n            TypeDeclarationField (Start: 41 , End: 140, On: input.raml, Source: KeyValueNodeImpl)\n                SYStringNode: \"root\" (Start: 41 , End: 45, On: input.raml)\n                TypeDeclarationNode (Start: 51 , End: 140, On: input.raml, Source: SYObjectNode)\n                    FacetNode (Start: 51 , End: 110, On: input.raml, Source: KeyValueNodeImpl)\n                        SYStringNode: \"properties\" (Start: 51 , End: 61, On: input.raml)\n                        SYObjectNode (Start: 69 , End: 110, On: input.raml)\n                            PropertyNode (Start: 69 , End: 81, On: input.raml, Source: KeyValueNodeImpl)\n                                SYStringNode: \"name\" (Start: 69 , End: 73, On: input.raml)\n                                TypeDeclarationNode (Start: 75 , End: 81, On: input.raml, Source: SYStringNode)\n                                    KeyValueNodeImpl (Start: -1 , End: 81)\n                                        StringNodeImpl: \"type\" (Start: -1 , End: -1)\n                                        NativeTypeExpressionNode: \"string\" (Start: 75 , End: 81, On: input.raml, Source: NativeTypeExpressionNode)\n                                    KeyValueNodeImpl (Start: -1 , End: -1)\n                                        StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                                        ObjectNodeImpl (Start: -1 , End: -1)\n                                            KeyValueNodeImpl (Start: -1 , End: -1)\n                                                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                                                OverlayableStringNode: \"name\" (Start: -1 , End: -1, Source: SYStringNode)\n                            PropertyNode (Start: 88 , End: 105, On: input.raml, Source: KeyValueNodeImpl)\n                                SYStringNode: \"friends\" (Start: 88 , End: 95, On: input.raml)\n                                TypeDeclarationNode (Start: 97 , End: 105, On: input.raml, Source: SYStringNode)\n                                    KeyValueNodeImpl (Start: -1 , End: 111)\n                                        StringNodeImpl: \"type\" (Start: -1 , End: -1)\n                                        ArrayTypeExpressionNode: Friend[] (Start: 103 , End: 111, On: input.raml, Source: ArrayTypeExpressionNode)\n                                            NamedTypeExpressionNode Friend -> {TypeDeclarationNode RefStart: 152 , RefEnd: 200} (Start: 103 , End: 109, On: input.raml, Source: NamedTypeExpressionNode)\n                                    KeyValueNodeImpl (Start: -1 , End: -1)\n                                        StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                                        ObjectNodeImpl (Start: -1 , End: -1)\n                                            KeyValueNodeImpl (Start: -1 , End: -1)\n                                                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                                                OverlayableStringNode: \"friends\" (Start: -1 , End: -1, Source: SYStringNode)\n                    FacetNode (Start: 110 , End: 137, On: input.raml, Source: KeyValueNodeImpl)\n                        SYStringNode: \"additionalProperties\" (Start: 110 , End: 130, On: input.raml)\n                        SYBooleanNode: false (Start: 132 , End: 137, On: input.raml)\n                    KeyValueNodeImpl (Start: -1 , End: -1)\n                        StringNodeImpl: \"type\" (Start: -1 , End: -1)\n                        NativeTypeExpressionNode: \"object\" (Start: -1 , End: -1)\n                    KeyValueNodeImpl (Start: -1 , End: -1)\n                        StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                        ObjectNodeImpl (Start: -1 , End: -1)\n                            KeyValueNodeImpl (Start: -1 , End: -1)\n                                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                                OverlayableStringNode: \"root\" (Start: -1 , End: -1, Source: SYStringNode)\n            TypeDeclarationField (Start: 140 , End: 200, On: input.raml, Source: KeyValueNodeImpl)\n                SYStringNode: \"Friend\" (Start: 140 , End: 146, On: input.raml)\n                TypeDeclarationNode (Start: 152 , End: 200, On: input.raml, Source: SYObjectNode)\n                    KeyValueNodeImpl (Start: 152 , End: 164, On: input.raml)\n                        SYStringNode: \"type\" (Start: 152 , End: 156, On: input.raml)\n                        NativeTypeExpressionNode: \"object\" (Start: 158 , End: 164, On: input.raml, Source: SYStringNode)\n                    FacetNode (Start: 169 , End: 200, On: input.raml, Source: KeyValueNodeImpl)\n                        SYStringNode: \"properties\" (Start: 169 , End: 179, On: input.raml)\n                        SYObjectNode (Start: 187 , End: 200, On: input.raml)\n                            PropertyNode (Start: 187 , End: 199, On: input.raml, Source: KeyValueNodeImpl)\n                                SYStringNode: \"name\" (Start: 187 , End: 191, On: input.raml)\n                                TypeDeclarationNode (Start: 193 , End: 199, On: input.raml, Source: SYStringNode)\n                                    KeyValueNodeImpl (Start: -1 , End: 199)\n                                        StringNodeImpl: \"type\" (Start: -1 , End: -1)\n                                        NativeTypeExpressionNode: \"string\" (Start: 193 , End: 199, On: input.raml, Source: NativeTypeExpressionNode)\n                                    KeyValueNodeImpl (Start: -1 , End: -1)\n                                        StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                                        ObjectNodeImpl (Start: -1 , End: -1)\n                                            KeyValueNodeImpl (Start: -1 , End: -1)\n                                                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                                                OverlayableStringNode: \"name\" (Start: -1 , End: -1, Source: SYStringNode)\n                    KeyValueNodeImpl (Start: -1 , End: -1)\n                        StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                        ObjectNodeImpl (Start: -1 , End: -1)\n                            KeyValueNodeImpl (Start: -1 , End: -1)\n                                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                                OverlayableStringNode: \"Friend\" (Start: -1 , End: -1, Source: SYStringNode)\n    ResourceNode (Start: 200 , End: 423, On: input.raml, Source: KeyValueNodeImpl)\n        SYStringNode: \"/res\" (Start: 200 , End: 204, On: input.raml)\n        SYObjectNode (Start: 208 , End: 423, On: input.raml)\n            MethodNode (Start: 208 , End: 423, On: input.raml, Source: KeyValueNodeImpl)\n                SYStringNode: \"get\" (Start: 208 , End: 211, On: input.raml)\n                SYObjectNode (Start: 217 , End: 423, On: input.raml)\n                    BodyNode (Start: 217 , End: 423, On: input.raml, Source: KeyValueNodeImpl)\n                        SYStringNode: \"body\" (Start: 217 , End: 221, On: input.raml)\n                        SYObjectNode (Start: 229 , End: 423, On: input.raml)\n                            KeyValueNodeImpl (Start: 229 , End: 423, On: input.raml)\n                                SYStringNode: \"application/xml\" (Start: 229 , End: 244, On: input.raml)\n                                TypeDeclarationNode (Start: 256 , End: 423, On: input.raml, Source: SYObjectNode)\n                                    KeyValueNodeImpl (Start: 256 , End: 266, On: input.raml)\n                                        SYStringNode: \"type\" (Start: 256 , End: 260, On: input.raml)\n                                        NamedTypeExpressionNode root -> {TypeDeclarationNode RefStart: 51 , RefEnd: 140} (Start: 262 , End: 266, On: input.raml, Source: SYStringNode)\n                                    ExampleDeclarationNode (Start: 277 , End: 423, On: input.raml, Source: KeyValueNodeImpl)\n                                        SYStringNode: \"example\" (Start: 277 , End: 284, On: input.raml)\n                                        ErrorNode: \"Error validating XML. Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'my-custom-xml'. One of '{\"http://validationnamespace.raml.org\":friends}' is expected.\" (Start: 286 , End: 423, On: input.raml, Source: SYStringNode)\n                                    KeyValueNodeImpl (Start: -1 , End: -1)\n                                        StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                                        ObjectNodeImpl (Start: -1 , End: -1)\n                                            KeyValueNodeImpl (Start: -1 , End: -1)\n                                                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                                                OverlayableStringNode: \"application/xml\" (Start: -1 , End: -1, Source: SYStringNode)\n                    KeyValueNodeImpl (Start: -1 , End: -1)\n                        StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                        ObjectNodeImpl (Start: -1 , End: -1)\n                            KeyValueNodeImpl (Start: -1 , End: -1)\n                                StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                                OverlayableStringNode: \"get\" (Start: -1 , End: -1, Source: SYStringNode)\n            KeyValueNodeImpl (Start: -1 , End: -1)\n                StringNodeImpl: \"displayName\" (Start: -1 , End: -1)\n                ObjectNodeImpl (Start: -1 , End: -1)\n                    KeyValueNodeImpl (Start: -1 , End: -1)\n                        StringNodeImpl: \"value\" (Start: -1 , End: -1)\n                        OverlayableStringNode: \"/res\" (Start: -1 , End: -1, Source: SYStringNode)\n")
     but: was  RamlDocumentNode (Start: 11 , End: 423, On: input.raml, Source: SYObjectNode) KeyValueNodeImpl (Start: 11 , End: 31, On: input.raml) SYStringNode: "title" (Start: 11 , End: 16, On: input.raml) OverlayableObjectNodeImpl (Start: 18 , End: 31, On: input.raml, Source: SYStringNode) KeyValueNodeImpl (Start: 11 , End: 31, On: input.raml) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "simple object" (Start: 18 , End: 31, On: input.raml) TypesNode (Start: 32 , End: 200, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "types" (Start: 32 , End: 37, On: input.raml) SYObjectNode (Start: 41 , End: 200, On: input.raml) TypeDeclarationField (Start: 41 , End: 140, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "root" (Start: 41 , End: 45, On: input.raml) TypeDeclarationNode (Start: 51 , End: 140, On: input.raml, Source: SYObjectNode) FacetNode (Start: 51 , End: 110, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "properties" (Start: 51 , End: 61, On: input.raml) SYObjectNode (Start: 69 , End: 110, On: input.raml) PropertyNode (Start: 69 , End: 81, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "name" (Start: 69 , End: 73, On: input.raml) TypeDeclarationNode (Start: 75 , End: 81, On: input.raml, Source: SYStringNode) KeyValueNodeImpl (Start: -1 , End: 81) StringNodeImpl: "type" (Start: -1 , End: -1) NativeTypeExpressionNode: "string" (Start: 75 , End: 81, On: input.raml, Source: NativeTypeExpressionNode) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "name" (Start: -1 , End: -1, Source: SYStringNode) PropertyNode (Start: 88 , End: 105, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "friends" (Start: 88 , End: 95, On: input.raml) TypeDeclarationNode (Start: 97 , End: 105, On: input.raml, Source: SYStringNode) KeyValueNodeImpl (Start: -1 , End: 111) StringNodeImpl: "type" (Start: -1 , End: -1) ArrayTypeExpressionNode: Friend[] (Start: 103 , End: 111, On: input.raml, Source: ArrayTypeExpressionNode) NamedTypeExpressionNode Friend -> {TypeDeclarationNode RefStart: 152 , RefEnd: 200} (Start: 103 , End: 109, On: input.raml, Source: NamedTypeExpressionNode) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "friends" (Start: -1 , End: -1, Source: SYStringNode) FacetNode (Start: 110 , End: 137, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "additionalProperties" (Start: 110 , End: 130, On: input.raml) SYBooleanNode: false (Start: 132 , End: 137, On: input.raml) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "type" (Start: -1 , End: -1) NativeTypeExpressionNode: "object" (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "root" (Start: -1 , End: -1, Source: SYStringNode) TypeDeclarationField (Start: 140 , End: 200, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "Friend" (Start: 140 , End: 146, On: input.raml) TypeDeclarationNode (Start: 152 , End: 200, On: input.raml, Source: SYObjectNode) KeyValueNodeImpl (Start: 152 , End: 164, On: input.raml) SYStringNode: "type" (Start: 152 , End: 156, On: input.raml) NativeTypeExpressionNode: "object" (Start: 158 , End: 164, On: input.raml, Source: SYStringNode) FacetNode (Start: 169 , End: 200, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "properties" (Start: 169 , End: 179, On: input.raml) SYObjectNode (Start: 187 , End: 200, On: input.raml) PropertyNode (Start: 187 , End: 199, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "name" (Start: 187 , End: 191, On: input.raml) TypeDeclarationNode (Start: 193 , End: 199, On: input.raml, Source: SYStringNode) KeyValueNodeImpl (Start: -1 , End: 199) StringNodeImpl: "type" (Start: -1 , End: -1) NativeTypeExpressionNode: "string" (Start: 193 , End: 199, On: input.raml, Source: NativeTypeExpressionNode) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "name" (Start: -1 , End: -1, Source: SYStringNode) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "Friend" (Start: -1 , End: -1, Source: SYStringNode) ResourceNode (Start: 200 , End: 423, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "/res" (Start: 200 , End: 204, On: input.raml) SYObjectNode (Start: 208 , End: 423, On: input.raml) MethodNode (Start: 208 , End: 423, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "get" (Start: 208 , End: 211, On: input.raml) SYObjectNode (Start: 217 , End: 423, On: input.raml) BodyNode (Start: 217 , End: 423, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "body" (Start: 217 , End: 221, On: input.raml) SYObjectNode (Start: 229 , End: 423, On: input.raml) KeyValueNodeImpl (Start: 229 , End: 423, On: input.raml) SYStringNode: "application/xml" (Start: 229 , End: 244, On: input.raml) TypeDeclarationNode (Start: 256 , End: 423, On: input.raml, Source: SYObjectNode) KeyValueNodeImpl (Start: 256 , End: 266, On: input.raml) SYStringNode: "type" (Start: 256 , End: 260, On: input.raml) NamedTypeExpressionNode root -> {TypeDeclarationNode RefStart: 51 , RefEnd: 140} (Start: 262 , End: 266, On: input.raml, Source: SYStringNode) ExampleDeclarationNode (Start: 277 , End: 423, On: input.raml, Source: KeyValueNodeImpl) SYStringNode: "example" (Start: 277 , End: 284, On: input.raml) ErrorNode: "Error validating XML. Error: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://validationnamespace.raml.org":my-custom-xml}'. One of '{"http://validationnamespace.raml.org":friends}' is expected." (Start: 286 , End: 423, On: input.raml, Source: SYStringNode) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "application/xml" (Start: -1 , End: -1, Source: SYStringNode) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "get" (Start: -1 , End: -1, Source: SYStringNode) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "displayName" (Start: -1 , End: -1) ObjectNodeImpl (Start: -1 , End: -1) KeyValueNodeImpl (Start: -1 , End: -1) StringNodeImpl: "value" (Start: -1 , End: -1) OverlayableStringNode: "/res" (Start: -1 , End: -1, Source: SYStringNode)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.raml.v2.parser.RamlBuilderTestCase.runTest(RamlBuilderTestCase.java:58)
        at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.raml.v2.parser.ApiTckTestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec
Running org.raml.v2.api.SystemPropertiesTestCase
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.raml.v2.api.LibraryTestCase
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec
Running org.raml.v2.api.SpecInterfacesV10TestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.155 sec
Running org.raml.v2.api.ValidationResultsTestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running org.raml.v2.api.SpecInterfacesV08TestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 sec
Running org.raml.v2.api.TypeDeclarationValidationTestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.raml.v2.api.ApiModelParserTestCase
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": "/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/diego.macias/mulesoft/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": "file:/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": "file:/Users/riteshpatani/work/RAML/java-parser/raml-java-parser/raml-parser-2/target/test-classes/org/raml/v2/api/v10/full/input.raml"
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
    >removed node "schemaPath": null
Tests run: 80, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.047 sec
Running org.raml.v2.api.DataTypeFragmentTestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.raml.v2.api.OdataV10TestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.084 sec
Running org.raml.v2.api.LeaguesV10TestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec
Running org.raml.v2.api.LimitErrorMessagesTestCase
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.06 sec
Running org.raml.v2.api.XmlExternalFileTestCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.raml.v2.xml_schema.TypeToXmlSchemaTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.112 sec

Results :

Failed tests:   runTest[xml-to-raml-type-validations.array-error](org.raml.v2.parser.RamlBuilderTestCase): (..)

Tests run: 592, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Raml Java Parser 2nd generation parent 1.0.31-SNAPSHOT:
[INFO] 
[INFO] Raml Java Parser 2nd generation parent ............. SUCCESS [  1.188 s]
[INFO] Yaml Grammar ....................................... SUCCESS [  6.735 s]
[INFO] Raml Java Parser 2nd generation .................... FAILURE [ 46.718 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  54.760 s
[INFO] Finished at: 2019-03-04T15:32:05-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project raml-parser-2: There are test failures.

**Comment by rpatani** [comment]
This issue is discussed in following thread and it helped resolve the issue. The testFailureIgnore is missing. 

https://stackoverflow.com/questions/36427868/failed-to-execute-goal-org-apache-maven-pluginsmaven-surefire-plugin2-12test
