### ISSUE TITLE
The springboot jar is deployed, resolving the external path RAML file, and the URL is not found

### ISSUE THREAD

**Issue by losthua** [raml-org/raml-java-parser#643]
Idea is running normally, jar deployment is parsing and error reporting。

 RamlModelResult ramlModelResult = new RamlModelBuilder().buildApi(rampUrl);

java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(Unknown Source)
	at sun.misc.URLClassPath.findResource(Unknown Source)
	at java.net.URLClassLoader$2.run(Unknown Source)
	at java.net.URLClassLoader$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:58)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at java.net.URLClassLoader.getResourceAsStream(Unknown Source)
	at org.raml.v2.api.loader.ClassPathResourceLoader.fetchResource(ClassPathResourceLoader.java:61)
	at org.raml.v2.api.loader.CompositeResourceLoader.fetchResource(CompositeResourceLoader.java:39)
	at org.raml.v2.api.loader.DefaultResourceLoader.fetchResource(DefaultResourceLoader.java:40)
	at org.raml.v2.api.loader.DefaultResourceLoader.fetchResource(DefaultResourceLoader.java:52)
	at org.raml.v2.api.RamlModelBuilder.getRamlContent(RamlModelBuilder.java:287)
	at org.raml.v2.api.RamlModelBuilder.getRamlContent(RamlModelBuilder.java:278)
	at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:88)

Aha! Link: https://mulesoft-roadmap.aha.io/features/APIRAML-34

**Comment by eduardo-rubio** [comment]
Please contact me if this issue is still valid. Thx. Edu.
