### ISSUE TITLE
RunTimeException error

### ISSUE THREAD

**Issue by hb308** [raml-org/raml-java-parser#680]
Hi, I get this error when running.

Exception in thread "main" java.lang.RuntimeException: Builder not found for <NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=(products))>; valueNode=<org.yaml.snakeyaml.nodes.SequenceNode (tag=tag:yaml.org,2002:seq, value=[<org.yaml.snakeyaml.nodes.MappingNode (tag=tag:yaml.org,2002:map, values={ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=name)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=name)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=Core)>> }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=type)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=type)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=airline)>> })>, <org.yaml.snakeyaml.nodes.MappingNode (tag=tag:yaml.org,2002:map, values={ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=name)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=name)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=Promotion and Awards)>> }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=type)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=type)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=airline)>> })>])>>
        at org.raml.parser.builder.DefaultTupleBuilder.getBuilderForTuple(DefaultTupleBuilder.java:68)
        at org.raml.parser.visitor.YamlDocumentBuilder.onTupleStart(YamlDocumentBuilder.java:272)
        at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:145)
        at org.raml.parser.visitor.NodeVisitor.visitDocument(NodeVisitor.java:209)
        at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:90)
        at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:102)
        at org.nextstate.MockServer.<init>(MockServer.java:39)
        at org.nextstate.MockServerStandalone.main(MockServerStandalone.java:23)

FAILURE: Build failed with an exception.

Does this support RAML 1.0?

**Comment by jstoiko** [comment]
Please note that this parser is now deprecated and is about to be archived, please use [webapi-parser](https://github.com/raml-org/webapi-parser) moving forward.
