### ISSUE TITLE
java.lang.NoSuchFieldError: VALUE for v0.8.11

### ISSUE THREAD

**Issue by thanethomson** [raml-org/raml-java-parser#69]
A while back I incorporated v0.8.11 into an application of mine running on Play v2.3.8 and just yesterday upgraded to Play v2.4.0, where it seems to have reattempted to download the RAML parser (still v0.8.11). Now, when I start up my application, I get the following exception:

```
[ERROR] [07/01/2015 22:51:04.416] [application-akka.actor.default-dispatcher-2] [ActorSystem(application)] Uncaught fatal error from thread [application-akka.actor.default-dispatcher-2] shutting down ActorSystem [application]
java.lang.NoSuchFieldError: VALUE
	at org.raml.parser.utils.NodeUtils.<clinit>(NodeUtils.java:34)
	at org.raml.parser.visitor.NodeVisitor.resolveTag(NodeVisitor.java:164)
	at org.raml.parser.visitor.NodeVisitor.doVisitMappingNode(NodeVisitor.java:139)
	at org.raml.parser.visitor.NodeVisitor.visitDocument(NodeVisitor.java:209)
	at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:90)
	at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:107)
...
```

It seems as though one of your most recent commits has something to do with the removal of the `Tag.VALUE` static member - would this perhaps have anything to do with the new error I'm getting? None of my code usage of the RAML parser has changed.

**Comment by thanethomson** [comment]
Ah, I see that the Play Framework (v.2.4.0) forcibly depends on snakeyaml v1.15, and so overrides my attempts to include v1.13. Using `raml-java-parser` v0.9-SNAPSHOT works for me at the moment.
