### ISSUE TITLE
Nullpointer exception while invoking the RamlDocumentBuilder build method.

### ISSUE THREAD

**Issue by antoaravinth** [raml-org/raml-java-parser#74]
Hi, 

I have cloned your repo and built an jar using mvn. And then I tried to use it in my java project, where I have this little code:

```
import org.raml.parser.visitor.RamlDocumentBuilder;

/**
 * Created by anto_belgin on 04/08/15.
 */
public class Raml {
    public static void main(String[] args) {
       new RamlDocumentBuilder().build("/Users/anto_belgin/Downloads/api.yaml");
    }
}
```

and the content of the `api.yaml` is :

```
#%RAML 0.8
---
title: Leagues API
version: v1
baseUri: http://localhost/api
documentation:
    - title: Employees
      content: |
        Welcome to the _Employees API_ Documentation. The _Employees API_
        allows you to view a complete list of your employees. You may also
        add or delete employees to keep the list up to date.
    - title: Contact
      content: |
        If you need support, please contact asr@mulesoft.com.
```

(taken from your test case examples).

When I run the above java code, I get an error like this:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/bin/java -Didea.launcher.port=7536 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/htmlconverter.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/anto_belgin/programs/Java/raml-ip/out/production/raml-ip:/Users/anto_belgin/jars/groovy-custom/lib/ant-1.9.4.jar:/Users/anto_belgin/jars/groovy-custom/lib/ant-antlr-1.9.4.jar:/Users/anto_belgin/jars/groovy-custom/lib/ant-junit-1.9.4.jar:/Users/anto_belgin/jars/groovy-custom/lib/ant-launcher-1.9.4.jar:/Users/anto_belgin/jars/groovy-custom/lib/bsf-2.4.0.jar:/Users/anto_belgin/jars/groovy-custom/lib/commons-cli-1.2.jar:/Users/anto_belgin/jars/groovy-custom/lib/commons-logging-1.2.jar:/Users/anto_belgin/jars/groovy-custom/lib/gpars-1.2.1.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-ant-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-bsf-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-console-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-docgenerator-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-groovydoc-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-groovysh-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-jmx-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-json-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-jsr223-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-nio-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-servlet-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-sql-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-swing-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-templates-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-test-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-testng-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/groovy-xml-2.5.0-SNAPSHOT.jar:/Users/anto_belgin/jars/groovy-custom/lib/hamcrest-core-1.3.jar:/Users/anto_belgin/jars/groovy-custom/lib/ivy-2.4.0.jar:/Users/anto_belgin/jars/groovy-custom/lib/jansi-1.11.jar:/Users/anto_belgin/jars/groovy-custom/lib/jcommander-1.47.jar:/Users/anto_belgin/jars/groovy-custom/lib/jline-2.12.jar:/Users/anto_belgin/jars/groovy-custom/lib/jsp-api-2.0.jar:/Users/anto_belgin/jars/groovy-custom/lib/jsr166y-1.7.0.jar:/Users/anto_belgin/jars/groovy-custom/lib/junit-4.12.jar:/Users/anto_belgin/jars/groovy-custom/lib/multiverse-core-0.7.0.jar:/Users/anto_belgin/jars/groovy-custom/lib/openbeans-1.0.jar:/Users/anto_belgin/jars/groovy-custom/lib/qdox-1.12.1.jar:/Users/anto_belgin/jars/groovy-custom/lib/servlet-api-2.4.jar:/Users/anto_belgin/jars/groovy-custom/lib/testng-6.8.13.jar:/Users/anto_belgin/jars/groovy-custom/lib/xmlpull-1.1.3.1.jar:/Users/anto_belgin/jars/groovy-custom/lib/xstream-1.4.7.jar:/Users/anto_belgin/programs/Java/raml-ip/lib/raml-parser-0.9-SNAPSHOT.jar:/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain Raml
Exception in thread "main" java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
	at org.raml.parser.utils.StreamUtils.reader(StreamUtils.java:45)
	at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:102)
	at org.raml.parser.visitor.YamlDocumentBuilder.build(YamlDocumentBuilder.java:78)
	at Raml.main(Raml.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

I wonder why its giving NPE. But however, I could able to validate the same yaml file using the same jar:

```
java -jar aml-parser-0.9-SNAPSHOT.jar api.yaml 
```

gives me:

```
Validation Results for api.yaml:
	OK.
```

Kindly let me know where I'm making mistake!

**Comment by quilicicf** [comment]
Hi, 

I had the same error and fixed it by using a path prefixed by "file://". See examples below: 

```java
new RamlDocumentBuilder().build("file:///home/me/raml/api.raml");
```

or 

```java
URL url = getClass().getResource("raml/api.raml");
Raml raml = new RamlDocumentBuilder().build(url.toString());
```

Does it work for you ?

**Comment by blakeembrey** [comment]
@quilicicf Thanks for the pointer, it helped me fix the same issue.

Maybe this could exist in the README?

**Comment by yyamano** [comment]
I believe the patch at https://gist.github.com/yyamano/6419f409c0cbf11ee3b7 fixes the issue.

@blakeembrey Do you want me to send a pull request?

**Comment by blakeembrey** [comment]
@yyamano You're welcome to, I don't have any permissions over the repo but if there's tests included I'll try to make sure someone reviews it and gets it released.

**Comment by yyamano** [comment]
@blakeembrey I thought you have a commit bit:-) Anyway, just sent a pull request. See #102
